# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 03:24
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='news.NewsCategory'),
        ),
    ]
