# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=models.CharField(default='Author', max_length=50),
        ),
    ]
