# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 17:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_newspage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
